### PR TITLE
feat: integrate ada handle

### PR DESCRIPTION
**Pull request by sk-tenba**
https://app.asana.com/0/1203842063837585/1203857184580238

### CODE REVIEW

**Comment by sk-tenba** [comment]
image

**Review by sk-shishi — APPROVED** [review]
This will add slight overhead on several requests, but it's acceptable for now.

**Review by sk-kitsune — CHANGES_REQUESTED** [review]
⛔ **Changes requested**: there are blocking issues.

----


please don't do this, let's discuss

**Comment by sk-tenba** [comment]
close for better implementation in another pr

**Pull request closed without merging**
