### PR TITLE
feat: kreate logo

### PR DESCRIPTION
**Pull request by sk-tenba**
https://app.asana.com/0/1203849283056227/1204190863915000

### CODE REVIEW

**Comment by sk-tenba** [comment]
[Screencast from 16-03-2023 21:44:44.webm](https://user-images.githubusercontent.com/110231356/225654123-4b4570aa-4138-47c8-b3af-78aa6eeaa5fd.webm)

**Comment by sk-tenba** [comment]
[Screencast from 16-03-2023 21:45:58.webm](https://user-images.githubusercontent.com/110231356/225654210-b8e04a07-d3f8-491f-bc0a-5be035b32716.webm)

**Comment by sk-tenba** [comment]
[Screencast from 16-03-2023 22:40:26.webm](https://user-images.githubusercontent.com/110231356/225671852-68f87388-0eab-402b-aacc-de6f0ad3adaf.webm)

**Comment by sk-kitsune** [comment]
Moved to https://github.com/teiki-network/teiki-web/pull/91

**Pull request closed without merging**
